=== harperjiang/gdc-simulator/GDCSimulator/data/cloud.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://gdc.clarkson.edu/cloud"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://gdc.clarkson.edu/cloud">

	<xsd:complexType name="datacenterType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:element name="location" type="pointType" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="latency" type="xsd:int"/>
		<xsd:attribute name="datafile" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="datacentersType">
		<xsd:sequence maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="datacenter" type="datacenterType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="pointType">
		<xsd:attribute name="x" type="xsd:double"/>
		<xsd:attribute name="y" type="xsd:double"/>
	</xsd:complexType>


	<xsd:complexType name="clientType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:element name="location" type="pointType" />
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="workload_file" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="clientsType">
		<xsd:sequence maxOccurs="unbounded" minOccurs="1">
			<xsd:element name="client" type="clientType" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="cloudType">
		<xsd:sequence maxOccurs="1" minOccurs="1">
			<xsd:element name="config" type="configType" />
			<xsd:element name="datacenters" type="datacentersType" />
			<xsd:element name="clients" type="clientsType" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="cloud" type="cloudType" />

    <xsd:complexType name="configType">
    	<xsd:attribute name="unit" type="xsd:int"/>
    </xsd:complexType>
</xsd:schema>

=== harperjiang/gdc-simulator/GDCSimulator/data/cloud.xml
<?xml version="1.0" encoding="UTF-8"?>
<cloud xmlns="http://gdc.clarkson.edu/cloud" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://gdc.clarkson.edu/cloud cloud.xsd ">
	<config unit="1000" />
	<datacenters>
		<datacenter id="dca" latency="1" datafile="data_site1.txt">
			<location x="0.0" y="0.0" />
		</datacenter>
		<datacenter id="dcb" latency="1" datafile="data_site2.txt">
			<location x="0.0" y="0.0" />
		</datacenter>
		<datacenter id="dcc" latency="1" datafile="data_site3.txt">
			<location x="0.0" y="0.0" />
		</datacenter>
		<datacenter id="dcd" latency="1" datafile="data_site4.txt">
			<location x="0.0" y="0.0" />
		</datacenter>
		<datacenter id="dce" latency="1" datafile="data_site5.txt">
			<location x="0.0" y="0.0" />
		</datacenter>
	</datacenters>
	<clients>
		<client id="clienta" workload_file="uniform_workload2">
			<location x="0.0" y="0.0" />
		</client>
		<client id="clientb" workload_file="uniform_workload2">
			<location x="0.0" y="0.0" />
		</client>
	</clients>
</cloud>
